[package]
name = "hellowasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
image-base64-wasm = "0.6.0"
wasmprinter = "0.2.51"


